# fly.toml app configuration file generated for insightful-orders
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'insightful-orders'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.http_checks]
    interval = "15s"
    timeout = "10s"
    grace_period = "60s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "sh -lc 'CONFIG=production FLASK_APP=app:create_app flask db upgrade'"